### ISSUE TITLE
测试图片都出现错误

### ISSUE THREAD

**Issue by BanDianMan** [1974525360/table_ocr#1]
{     "msg": "'float' object is not subscriptable",     "code": 500 }

**Comment by zmsmao** [comment]
请问是哪张测试图片和哪个接口。

**Comment by BanDianMan** [comment]
使用的是如下图片 : ￼

错误信息 : 经过Debug是提取识别结构导致
￼

**Comment by zmsmao** [comment]
能具体路径上的图片和具体的哪个接口吗，GitHub这边是看不了你发的图片或者是截图。

**Comment by BanDianMan** [comment]
系统 : Mac OS 
架构 : Arm
错误接口路径 : /process/vidImg
错误图片路径: io/input_path/result/2/0001.jpg

**Comment by zmsmao** [comment]
系统 : Mac OS 这块我没试过，在window和linux是支持转换的， 你可以尝试自己修复一下。
